### PR TITLE
Fix/display permissions update results - solution for issue #21

### LINKED ISSUE #21: When creating new Functions, Rules or Roles in Admin UI, no Results are displayed
When creating new Functions, Rules or Roles in Admin UI, no Result in textbox is displayed, but transaction does get executed.

### PR DESCRIPTION
**Pull request by bassiebangura**
-Resolves #21 
Updated how the state, that represents results from the transactions mentioned in issue #21 is handled, by localizing the state to the Modal where the transaction occurs - this solved the issue.

### CODE REVIEW

File: src/components/PermissionsEditor.jsx [hunk 1]
```diff
@@ -38,8 +38,9 @@ class Editor extends Component {
       .then((res) => res.json || res)
       .then((res) => res.result || res)
       .then((res) => {
+        console.log("response", res)
```
Comment (Tr3yb0) [inline src/components/PermissionsEditor.jsx]: can you remove this console.log?

Comment (bassiebangura) [reply src/components/PermissionsEditor.jsx]: Sure thing

**Review by Tr3yb0 — APPROVED** [review]
